//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTGIAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTGIAY()
        {
            this.SANPHAMs = new HashSet<SANPHAM>();
        }
    
        public int IDCTGIAY { get; set; }
        public Nullable<int> IDLOAISP { get; set; }
        public Nullable<int> IDSIZEGIAY { get; set; }
        public Nullable<int> IDTHGIAY { get; set; }
        public Nullable<int> IDMAUSAC { get; set; }
    
        public virtual LOAISP LOAISP { get; set; }
        public virtual MAUSAC MAUSAC { get; set; }
        public virtual SIZEGIAY SIZEGIAY { get; set; }
        public virtual THGIAY THGIAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}
