//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class NGUOIDUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGUOIDUNG()
        {
            HINH = "~/Areas/Admin/Content/img/iconanh.png";
            this.CUAHANGs = new HashSet<CUAHANG>();
            this.DANHGIASPs = new HashSet<DANHGIASP>();
            this.DONHANGs = new HashSet<DONHANG>();
        }
        [NotMapped]
        public HttpPostedFileBase UploadImage1 { get; set; }
        public int IDND { get; set; }
        public string TENND { get; set; }
        public string EMAIL { get; set; }
        public string MATKHAU { get; set; }
        public string NHAPLAIMK { get; set; }
        public string SDT { get; set; }
        public string DIACHI { get; set; }
        public Nullable<int> IDPQND { get; set; }
        public string HINH { get; set; }
        public Nullable<int> IDVOUCHERSHOP { get; set; }
        public Nullable<int> IDVOUCHER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUAHANG> CUAHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIASP> DANHGIASPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
        public virtual PQNGUOIDUNG PQNGUOIDUNG { get; set; }
        public virtual VOUCHERSHOP VOUCHERSHOP { get; set; }
        public virtual VOUCHER VOUCHER { get; set; }
    }
}
