//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CTDONHANGs = new HashSet<CTDONHANG>();
            this.DANHGIASPs = new HashSet<DANHGIASP>();
        }

        [NotMapped]
        public HttpPostedFileBase UploadImage1 { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImage2 { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImage3 { get; set; }

        public int IDSANPHAM { get; set; }
        public string TENSP { get; set; }
        public string HINHANH1 { get; set; }
        public string HINHANH2 { get; set; }
        public string HINHANH3 { get; set; }
        public string MOTASANPHAM { get; set; }
        public Nullable<int> GIABAN { get; set; }
        public Nullable<int> PHANTRAMGIAM { get; set; }
        public Nullable<int> GIAGIAM { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<int> IDPHEDUYET { get; set; }
        public Nullable<int> IDCUAHANG { get; set; }
        public Nullable<int> IDLOAISP { get; set; }
        public Nullable<int> SOLUONGTON { get; set; }
        public Nullable<int> IDCTDIENTHOAI { get; set; }
        public Nullable<int> IDCTTHOITRANG { get; set; }
        public Nullable<int> IDCTGIAY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDONHANG> CTDONHANGs { get; set; }
        public virtual CUAHANG CUAHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIASP> DANHGIASPs { get; set; }
        public virtual LOAISP LOAISP { get; set; }
        public virtual PHEDUYET PHEDUYET { get; set; }
        public virtual CTDIENTHOAI CTDIENTHOAI { get; set; }
        public virtual CTGIAY CTGIAY { get; set; }
        public virtual CTTHOITRANG CTTHOITRANG { get; set; }
    }
}
